name: Page Build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Page
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn global add vuepress
      - name: Build Site
        run: vuepress build .
      - name: Take Stock
        run: ls .
