name: Page Build

on:
  push:
    branch:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Page
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install -y lftp && yarn install --dev --frozen-lockfile
      - name: Build Site
        run: yarn docs:build
      - name: Deploy
        run: lftp -e "set ssl:verify-certificate false; open $remote_host; user $remote_user $remote_pass; mirror --exclude .htaccess --reverse --delete --recursion=always -vvv docs/.vuepress/dist/ ."
        env:
          remote_host: ${{ secrets.DOCS_DEPLOY_HOST }}
          remote_user: ${{ secrets.DOCS_DEPLOY_USER }}
          remote_pass: ${{ secrets.DOCS_DEPLOY_PASS }}
